development:
  adapter: postgresql
  encoding: unicode
  database: sampleapp_development
  pool: 5
  host: localhost
  port: 5432
  username: nunoesteves
  
test: &test
  adapter: postgresql
  encoding: unicode
  database: sampleapp_test
  pool: 5
  host: localhost
  port: 5432
  username: nunoesteves
cucumber:
  <<: *test